### ISSUE TITLE
[bug] ref_indices contains values

### ISSUE THREAD

**Issue by ggbioing** [Jfortin1/neuroCombat#1]
https://github.com/Jfortin1/neuroCombat/blob/cab18534be578779fda3ac1440c029f6450f8cbf/neuroCombat/neuroCombat.py#L95

The following line solves the bug:
`ref_indices = np.argwhere(covars[:, batch_col] == ref_batch).squeeze()`

**Comment by Jfortin1** [comment]
Fixed in https://github.com/Jfortin1/neuroCombat/commit/77d526b5118f466c33b5325a0f7e300880b4b7c4. Thanks!
