### ISSUE TITLE
Handling of features that are constant across all sites and subjects

### ISSUE THREAD

**Issue by pedrob37** [Jfortin1/neuroCombat#10]
I'm trying to use NeuroCombat for segmentation harmonisation. I have GM, WM, and CSF segmentations for many subjects and sites, and am using the individual voxel values as features. As expected, there are voxels that end up being zero across all sites and subjects even if skull-stripping is performed: E.g.: For the CSF maps, in the central WM regions the voxel values are all zero for all images.

My understanding is that this poses problems for the NeuroCombat model as these features will have zero mean and variance. I can of course simply remove those voxels that exhibit this behaviour, but I wanted to check that this is the best course of action before doing so.

**Comment by Jfortin1** [comment]
Hi @pedrob37, yes, that would be my strategy (remove the constant rows, harmonize the data, and put back the constant rows).
