### ISSUE TITLE
Combat for non-uniform data?

### ISSUE THREAD

**Issue by diegoaper** [Jfortin1/neuroCombat#12]
Hello, we are trying to run Combat with "raw" BOLD images (4D images per subject). The datasets are from 2 different sites, one used a TR of 2sec and the other used TR of 0.8sec. This means that the number of volumes, in the same time range, would be more for the 0.8sec TR. One dataset has 177 volumes (2sec TR) and the other has 450 volumes (0.8sec TR). In summary is it possible to use a non-square matrix to run Combat for these two datasets? The variable in question is the "dat" variable with a (p x n) composition.

**Comment by Jfortin1** [comment]
Hi @diegoaper, I don't think ComBat could be used on this as it is, at least not without major changes in the methodology/model used.

**Comment by diegoaper** [comment]
Thank you
