### ISSUE TITLE
 Singular matrix during inversion

### ISSUE THREAD

**Issue by xuesongwang** [Jfortin1/neuroCombat#13]
Hi there,
  Thank you for this amazing project. I was using this [ADHD200](https://www.nitrc.org/frs/?group_id=383)  dataset to remove site effects. I computed Pearson coefficients for AAL functional connectivities as inputs and some sites have provided biological features such as gender, handedness and IQs. However, when calling the neuroCombat , I got the following error on this function `get_beta_with_nan`:
`LinAlgError:Singular matrix` 

https://github.com/Jfortin1/neuroCombat/blob/ac82a067412078680973ddf72bd634d51deae735/neuroCombat/neuroCombat.py#L211-L221

I am no experts in maths, but according to this [solution](https://stackoverflow.com/questions/10326015/singular-matrix-issue-with-numpy), it can be attributed to the same rows in the matrix so the inversion does not exist. I didn't fully understand this part of the code, but I guess I can have some patients who have the same biological features and that caused the issue? (assumption though). After I changed `la.inv` into `la.pinv` everything works fine now. I was wondering if you could have better insights towards this and whether modification is solid.

Thanks for the help :)

**Comment by Jfortin1** [comment]
Hi @xuesongwang, 

`LinAlgError:Singular matrix` usually means that some of the biological features are redundant (perfectly confounded) or highly correlated. Is this the case?

**Comment by Jfortin1** [comment]
Closing this as no answer from user.

**Comment by xuesongwang** [comment]
Sorry for the late but you are are right @Jfortin1 , I have one column called IQ measure and that can probably be inferred from three other columns. That might have result in zero determinant matrix or redundant  columns (hence non-invertible). many thanks
