### ISSUE TITLE
How to implement neuroCombat for voxel-wise data?

### ISSUE THREAD

**Issue by Melissa1909** [Jfortin1/neuroCombat#14]
Hey Jean-Philippe, 
thanks for the nice and helpful software! :) I have successfully used neuroCombat for Desikan-Killiany ROIs already, but I was trying to extend the analysis to voxel-wise data. However, the doc says that dat has to be of shape = (features, samples) e.g. cortical thickness measurements, image voxels. How do I put 3D voxel information into 1 dimension? How can I input voxel-wise data per subject into neuroCombat?
Best, Melissa

**Comment by Jfortin1** [comment]
@Melissa1909 Assuming your images are registered to a common template, you could simply transform for each image the 3d array of voxel intensities into a long 1d vector by concatenating the slides. That way you get one long vector per image, and you can create a matrix where each column is one image. Then you can apply neuroCombat on the matrix,, and transform back each harmonized column into a 3d array with the original dimensions. We don't provide code to do that, but there are plenty of examples out there that explain how to convert a 3d array into a 1d vector in python.
