### ISSUE TITLE
cannot xtfrm data frames

### ISSUE THREAD

**Issue by stevencenusc** [Jfortin1/neuroCombat#17]
Warning message:
In xtfrm.data.frame(x) : cannot xtfrm data frames

How to fix this warning message?

**Comment by Jfortin1** [comment]
@stevencenusc This does not seem to be an error related to the Python package but rather to the R package; this issue should be raised here: https://github.com/Jfortin1/neuroCombat_Rpackage/

Also, please provide a reproducible example and code.
