### ISSUE TITLE
batch_levels of type "words" (e.g. "siteA") raise an error

### ISSUE THREAD

**Issue by ggbioing** [Jfortin1/neuroCombat#2]
https://github.com/Jfortin1/neuroCombat/blob/cab18534be578779fda3ac1440c029f6450f8cbf/neuroCombat/neuroCombat.py#L107

**Comment by Jfortin1** [comment]
Fixed in https://github.com/Jfortin1/neuroCombat/commit/f50dd2dfba0c07d5a602f5cc0ea63c73e9969f75. Thanks!
