### ISSUE TITLE
Sample or dummy data available?

### ISSUE THREAD

**Issue by fluese** [Jfortin1/neuroCombat#4]
Hi,

I would like to try Combat for harmonizing results of clinical data from quite a lot of scanners. However, I am struggling with the right inputs. Are sample or dummy data available? Or could you elaborate a bit more, like in the short Matlab script / tutorial?

Best,
Falk

**Comment by Jfortin1** [comment]
@fluese I just added a few notes here: https://github.com/Jfortin1/neuroCombat/blob/master/README.md@fku

Let me know if this is useful.
