### ISSUE TITLE
Negative output

### ISSUE THREAD

**Issue by jche058** [Jfortin1/neuroCombat#5]
I was a new user of NeuroCombat. We have multi-site dwi image, before Combat DTI matrices showed site effect, combat was worked great to removed site effect. For the same data set we also have a measurement from Mrtrix3, this matrix didn't have site effect before combat, however, I thought may just apply the approach for all the matrices. For this Mrtrix3 matrix, we have found some negative value after combat, which is feasible. How this could happen and is there a way to control not being negative?

Jian

**Comment by Jfortin1** [comment]
Hi @jche058, 

What is the scale/range of the measurements for the matrices obtained from Mrtrix3?

**Comment by jche058** [comment]
3.9 e-05 (1.4e-05 ~ 7.9e-04)
Thanks

**Comment by CaitlinLloyd** [comment]
Hi, just wondering if there were any updates on this issue? I am attempting to harmonise MRtrix streamline count matrices and getting some negative values after harmonising (for counts at the lower end of the range). Is there a way of constraining to zero? Thank you!

**Comment by Jfortin1** [comment]
Hi @CaitlinLloyd @jche058,

Given that ComBat uses a linear model, there is no straightforward way to constraint the harmonized values to 0.

One obvious solution, which works well in practice for most applications, is to shift the harmonized data by a small constant, something like
`data_harmonized = data_harmonized + abs(min(data_harmonized))`

Another solution is to first unconstraint your data by mapping them to the [-Inf, Inf] domain, for instance using a logit transformation, perform harmonization, and then map back the harmonized data to its original scale using the reverse transformation. This approach does assume that the scanner/batch effects are linear once the data have been transformed into the [-Inf, Inf] domain.
