### ISSUE TITLE
Is the information contained in the ‘covar’ regressed or preserved?

### ISSUE THREAD

**Issue by gourdchen** [Jfortin1/neuroCombat#6]
I see the documnets of R implementation, the demographic infomation will be protected. I don't know the condition in the Python implementation.

**Comment by Jfortin1** [comment]
They are preserved, it's indeed not so clear from our doc. Just improved on that in https://github.com/Jfortin1/neuroCombat/commit/defdb9ceca6570304c13aefecf4b14a50649d12b.
